const MOCK_REQUESTS = [
  {
    id: "REQ-001",
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    graduationYear: "2018",
    department: "Computer Science & Engineering",
    currentCompany: "Google",
    currentPosition: "Senior Software Engineer",
    submittedAt: "2023-05-15T10:30:00Z",
    status: "pending",
    // All other fields from the registration form would be here
    batch: "2014-2018",
    phone: "+1234567890",
    address: "123 Tech Street, San Francisco, CA",
    studentId: "CS-2014-042",
    experience: "5",
    skills: ["JavaScript", "React", "Node.js", "Cloud Computing"],
    interests: ["AI", "Machine Learning", "Web Development"],
    achievements:
      "Led a team that developed a new product feature that increased user engagement by 30%.",
    facebook: "https://facebook.com/johndoe",
    twitter: "https://twitter.com/johndoe",
    linkedin: "https://linkedin.com/in/johndoe",
    instagram: "https://instagram.com/johndoe",
  },
  {
    id: "REQ-002",
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    graduationYear: "2019",
    department: "Electrical Engineering",
    currentCompany: "Tesla",
    currentPosition: "Electrical Engineer",
    submittedAt: "2023-05-16T14:45:00Z",
    status: "approved",
    // All other fields from the registration form would be here
    batch: "2015-2019",
    phone: "+1987654321",
    address: "456 Energy Avenue, Palo Alto, CA",
    studentId: "EE-2015-028",
    experience: "4",
    skills: ["Circuit Design", "Power Systems", "AutoCAD", "Simulation"],
    interests: ["Renewable Energy", "Electric Vehicles", "Sustainable Design"],
    achievements: "Patent for an innovative battery cooling system.",
    facebook: "https://facebook.com/janesmith",
    twitter: "https://twitter.com/janesmith",
    linkedin: "https://linkedin.com/in/janesmith",
    instagram: "https://instagram.com/janesmith",
  },
  {
    id: "REQ-003",
    firstName: "Michael",
    lastName: "Johnson",
    email: "michael.johnson@example.com",
    graduationYear: "2020",
    department: "Business Administration",
    currentCompany: "Amazon",
    currentPosition: "Product Manager",
    submittedAt: "2023-05-17T09:15:00Z",
    status: "rejected",
    rejectionReason:
      "Unable to verify graduation information. Please provide additional documentation.",
    // All other fields from the registration form would be here
    batch: "2016-2020",
    phone: "+1122334455",
    address: "789 Commerce Road, Seattle, WA",
    studentId: "BA-2016-103",
    experience: "3",
    skills: ["Product Management", "Market Analysis", "Agile", "Leadership"],
    interests: ["E-commerce", "Digital Marketing", "Business Strategy"],
    achievements:
      "Launched a product that generated $2M in revenue in the first quarter.",
    facebook: "https://facebook.com/michaeljohnson",
    twitter: "https://twitter.com/michaeljohnson",
    linkedin: "https://linkedin.com/in/michaeljohnson",
    instagram: "https://instagram.com/michaeljohnson",
  },
  {
    id: "REQ-004",
    firstName: "Emily",
    lastName: "Williams",
    email: "emily.williams@example.com",
    graduationYear: "2021",
    department: "Mechanical Engineering",
    currentCompany: "Boeing",
    currentPosition: "Mechanical Design Engineer",
    submittedAt: "2023-05-18T11:20:00Z",
    status: "pending",
    // All other fields from the registration form would be here
    batch: "2017-2021",
    phone: "+1567891234",
    address: "101 Aviation Blvd, Chicago, IL",
    studentId: "ME-2017-056",
    experience: "2",
    skills: [
      "CAD",
      "Structural Analysis",
      "Fluid Dynamics",
      "Materials Science",
    ],
    interests: ["Aerospace", "Sustainable Design", "Robotics"],
    achievements:
      "Designed a component that reduced manufacturing costs by 15%.",
    facebook: "https://facebook.com/emilywilliams",
    twitter: "https://twitter.com/emilywilliams",
    linkedin: "https://linkedin.com/in/emilywilliams",
    instagram: "https://instagram.com/emilywilliams",
  },
  {
    id: "REQ-005",
    firstName: "David",
    lastName: "Brown",
    email: "david.brown@example.com",
    graduationYear: "2017",
    department: "Physics",
    currentCompany: "SpaceX",
    currentPosition: "Research Scientist",
    submittedAt: "2023-05-19T16:30:00Z",
    status: "approved",
    // All other fields from the registration form would be here
    batch: "2013-2017",
    phone: "+1654987321",
    address: "202 Rocket Lane, Hawthorne, CA",
    studentId: "PH-2013-019",
    experience: "6",
    skills: ["Data Analysis", "Simulation", "Python", "Research Methods"],
    interests: ["Space Exploration", "Quantum Physics", "Astrophysics"],
    achievements: "Published 3 papers in top-tier scientific journals.",
    facebook: "https://facebook.com/davidbrown",
    twitter: "https://twitter.com/davidbrown",
    linkedin: "https://linkedin.com/in/davidbrown",
    instagram: "https://instagram.com/davidbrown",
  },
];
