# Generated by Django 5.1.3 on 2025-04-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_userinfo_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
