# Generated by Django 5.1.3 on 2025-04-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_userinfo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='achievements',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='batch',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='current_company',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='current_position',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='experience',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='facebook',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='graduation_year',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='instagram',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='interests',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='linkedin',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='skills',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='twitter',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
