# Generated by Django 5.1.3 on 2025-04-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_userinfo_achievements_userinfo_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='batch',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
