# Generated by Django 5.1.3 on 2025-04-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_alter_userinfo_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='batch',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
