# Generated by Django 5.1.3 on 2025-04-29 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0006_alter_userinfo_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='batch',
        ),
    ]
