# Generated by Django 5.1.3 on 2025-04-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0008_userinfo_batch_alter_userinfo_graduation_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='facebook',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
