# Generated by Django 5.1.3 on 2025-05-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0010_alter_userinfo_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='interests',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='skills',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
