# Generated by Django 5.1.3 on 2024-12-02 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_job_email_alter_job_company_alter_job_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='Deadline',
            new_name='deadline',
        ),
    ]
