# Generated by Django 5.1.3 on 2025-04-29 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_post_created_by'),
        ('cms', '0003_event_image'),
    ]

    operations = [
    ]
