# Generated by Django 5.1.3 on 2024-11-24 19:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_blog_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='relationship',
        ),
        migrations.AddField(
            model_name='contact',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='cms.userprofile'),
        ),
        migrations.AddField(
            model_name='job',
            name='Deadline',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='jobType',
            field=models.CharField(default='Full-Time', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='blog',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='posted_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
