# Generated by Django 5.1.3 on 2025-05-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_merge_0002_alter_post_created_by_0003_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('graduationYear', models.IntegerField()),
                ('batch', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('studentId', models.CharField(max_length=255)),
                ('currentCompany', models.CharField(blank=True, max_length=255, null=True)),
                ('currentPosition', models.CharField(blank=True, max_length=255, null=True)),
                ('experience', models.IntegerField()),
                ('skills', models.TextField()),
                ('interests', models.TextField()),
                ('achievements', models.TextField()),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('cv', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('proofDocument', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('isApproved', models.BooleanField(default=False)),
                ('rejectionReason', models.TextField(blank=True, default='', null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
