# Generated by Django 5.1.3 on 2025-05-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_registrationrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationrequest',
            name='achievements',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='interests',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='skills',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
