# Generated by Django 5.1.3 on 2025-05-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_alter_registrationrequest_achievements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationrequest',
            name='interests',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='skills',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
